### ISSUE TITLE
I cant run this program / No puedo ejecutar este programa

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-worldeditor-old#1]
I cant open this program. Send 2 screenshots and paste worldeditor.ini
No puedo abrir este programa, mando 2 capturas de pantalla y pego worldeditor.ini

**worldeditor.ini**
[INDEX]
MaxGrhs=32000

[PATH]
DirGraficos=C:\ao-cliente-master\Graficos
DirMidi=C:\ao-cliente-master\MIDI
DirIndex=C:\world editor\GrhIndex
DirDats=C:\ao-cliente-master\INIT
DirWavs=C:\ao-cliente-master\WAV
DirMp3=C:\ao-cliente-master\MP3
UltimoMapa=290

[CONFIGURACION]
ObjTranslado=378
GuardarConfig=1
AutoCapturarTrans=1
AutoCapturarSup=0
UtilizarDeshacer=1

[CONFIGURACION]
ObjTranslado=378
GuardarConfig=1
AutoCapturarTrans=1
AutoCapturarSup=0
UtilizarDeshacer=1

[MOSTRAR]
LastPos=45-40
ControlAutomatico=1
Capa2=1	
Capa3=1
Capa4=0
Grilla=0
Triggers=0
Bloqueos=0
Translados=1
Objetos=1
NPCs=1

'----------------------
PantallaX=19
PantallaY=21
'----------------------
' AYUDA:
' en 800x600 se usa X = 14 y Y = 16
' en 1024x768 se usa X = 19 y Y = 21.
'----------------------
' el valor minimo es 3 en ambos.
' el valor maximo en X es 23 y en Y es 32.
'----------------------

ClienteHeight=13
ClienteWidth=17
' Configuracion grafica del cliente necesaria para detectar los bordes legales del mapa.
![codigo_error_we](https://user-images.githubusercontent.com/7727108/47833569-4c42e080-dd7a-11e8-81d7-2acf5d671f0b.jpg)

**Comment by RecoX** [comment]
Close this issue as this is not our code base.

As you can see in the file:
https://github.com/ao-libre/ao-worldeditor/blob/master/Codigo/modOreEngine.bas#L78

The line `StreamFile` is obtaining the data from `Particles.ini` meanwhile in our code is called `Particulas.ini`
